[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.start_db]
command = "surreal"
args = ["start", "memory", "-A", "--auth", "--user", "root", "--pass", "root"]

[tasks.start_smtp]
command = "mailtutan"

[tasks.start_dns]
command = "updns" # TODO: create config file and point to it here with -c

[tasks.start_server]
env = { "RUST_MIN_STACK" = 104857600 }
cwd = "C:\\Users\\bnhei\\source\\repos\\toadslop\\rush\\data_server_v2"
command = "cargo"
args = ["watch", "-x", "check", "-x", "test", "-x", "run"]

[tasks.udeps]
command = "cargo"
args = ["+nightly", "udeps"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.start]
run_task = { name = [
    "start_db",
    "start_smtp",
    "start_dns",
    "start_server",
], fork = true, parallel = true }
