# Should fail
POST http://localhost:8080/instance HTTP/1.1
accept: application/json
content-type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDAwMzE0MTcsIm5iZiI6MTcwMDAzMTQxNywiZXhwIjoxNzAwMDMyMzE3LCJpc3MiOiJTdXJyZWFsREIiLCJOUyI6InJvb3QiLCJEQiI6InJvb3QiLCJTQyI6ImFjY291bnQiLCJJRCI6ImFjY291bnQ64p-odGVzdDE1QHRlc3QuY29t4p-pIn0.bxPbNAzG5Iiva2wAD2LPBY5PBhZI--SbZwA-NCNrUH7ZJW9tfLz85iUwxzitx5K0xJb_gZnN8zkxC5RJ2QUMFw

{
    "name": "aa",
    "account_id": "test15@test.com"
}

###
POST http://localhost:8000/signup HTTP/1.1
content-type: 

{
    "ns": "root",
    "db": "root",
    "sc": "account",
    "email": "johndoe@dick.com",
    "name": "Black Box Inc",
    "password": "12345678"
}