### Successfully create an account
POST http://localhost:8080/account HTTP/1.1
content-type: application/json

{
    "name": "test15",
    "email": "test15@test.com",
    "password": "something"
}

### Sign in
POST http://localhost:8080/account/signin HTTP/1.1
content-type: application/json

{
    "email": "test15@test.com",
    "password": "something"
}

### Error
POST http://localhost:8080/account HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "",
    "password": ""
}

### signup
POST http://localhost:8000/signup HTTP/1.1
content-type: application/json
Accept: application/json

{
    "ns": "root",
    "db": "root",
    "sc": "account",
    "email": "tes3t@test.com",
    "password": "12345578333",
    "name": "My Cool Coorporation"
}
